services:
  php:
    build: .
    volumes:
      - ./html:/var/www/html
      - ./php-conf.d/php.ini:/usr/local/etc/php/conf.d/custom-php.ini:ro
    ports:
      - "80:80"
    extra_hosts:
      # add host.docker.internal for linux
      - host.docker.internal:host-gateway

  db:
    image: mariadb
    volumes:
      - ./mysql-conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  mysql-data:
